### ISSUE TITLE
Dependency error with langchain version 0.3.0

### ISSUE THREAD

**Issue by amiralichangizi** [langchain-ai/langchain-redis#16]
Hi, i received the current error after the last-day update of langchain-core and other libraries that are dependent on it.

here is the error : 
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
langchain-redis 0.0.4 requires langchain-core<0.3,>=0.1.52, but you have langchain-core 0.3.0 which is incompatible.
although I found the following on the pyproject.toml file , but langchain-redis version 0.0.4 requires version 0.2.40 langchain-core
`[tool.poetry.dependencies]
python = ">=3.9,<4.0"
langchain-core = "^0.3"
redisvl = "^0.3.3"
numpy = "^1"
python-ulid = "^2.7.0"`

**Comment by bsbodden** [comment]
@amiralichangizi Version `0.1.0` will be released  (in the next couple of days) which works with the new langchain-core >= 0.3
