### ISSUE TITLE
Dependency with redis stack server

### ISSUE THREAD

**Issue by pradeepdev-1995** [langchain-ai/langchain-redis#17]
```
Configuration
To use this package, you need to have a Redis instance running. You can configure the connection by setting the following environment variable:

export REDIS_URL="redis://username:password@localhost:6379"
```
In this configuration are we expecting **redis** or **redis stack server** to be run at localhost?

**Comment by bsbodden** [comment]
This integration should work as long as there's search and JSON support which comes preconfigured in Stack and Stack Server.
