### ISSUE TITLE
Use `config.embedding_dimensions` (if specified) in the RedisVectorStore instead of embedding dummy text.

### ISSUE THREAD

**Issue by AlirezaRoshanzamir** [langchain-ai/langchain-redis#35]
Thank you for your excellent library.

Making API calls or performing time-consuming tasks during module import or class initialization is a bad idea. You've already considered this by providing the `embedding_dimensions` argument and using a dummy embedding as a fallback method:

https://github.com/langchain-ai/langchain-redis/blob/2bdf379168b0cfe0b363b74d39dd9438e3de2e2d/libs/redis/langchain_redis/vectorstores.py#L273-L278

However, a few lines later, you didn't use the provided variable and embedded dummy text again:

https://github.com/langchain-ai/langchain-redis/blob/2bdf379168b0cfe0b363b74d39dd9438e3de2e2d/libs/redis/langchain_redis/vectorstores.py#L326-L335

**Comment by bsbodden** [comment]
Thanks for catching that! Will be addressed in the next release. Cheers.
