### ISSUE TITLE
Chat message memory without redis json module

### ISSUE THREAD

**Issue by GrozniyToaster** [langchain-ai/langchain-redis#7]
Hello

Following in the footsteps of the [previous proposal](https://github.com/langchain-ai/langchain/pull/25732)

I looked mainly at [chat message memory](https://github.com/langchain-ai/langchain-redis/blob/main/libs/redis/langchain_redis/chat_message_history.py#L44) 
It seems more optimized and cool, but it uses redis json 

This extension does not seem to be included in [vanilla redis](https://redis.io/docs/latest/develop/data-types/), which is available to everyone

Also, in teams where I work with LLM, uses keydb as an alternative to redis and it also does not support such specific modules

It seems to me that the implementation presented at [langchain_community](https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/chat_message_histories/redis.py) is also not bad and can work as an option if advanced redis is not used

Maybe it's worth adding an alternative implementation to this package?

**Comment by bsbodden** [comment]
Vanilla Redis (Redis Community Edition) is now what Redis Stack offers which includes Search+JSON. We will likely provide a implementation of this using Hashes also.
