### ISSUE TITLE
Unused torch dependency causing deployment failures due to overly large Docker image

### ISSUE THREAD

**Issue by dtan2-wiq** [langchain-ai/langchain-redis#9]
Hi there, thanks for your great work on this package. We've encountered an issue trying to use it, and we were wondering if you could look into it?

# Issue
`langchain-redis`'s dependency on torch increased our project's:
- build time: from 2 minutes to 10 minutes
- docker image size: from 1.9GB to 7GB

And our builds are timing out and failing

Our builds are not the concern of langchain-redis, but I'm sure this will be an issue other users who suddenly have to deal with much longer build times and larger build artifacts when they add `langchain-redis` as a dependency

# Suggestion

It appears that torch is specified as [a dependency in langchain-redis](https://github.com/search?q=repo%3Alangchain-ai%2Flangchain-redis%20torch&type=code) but not actually consumed/used anywhere in the code. Can we please remove this if it's not being used?

**Comment by bsbodden** [comment]
@dtan2-wiq thank you for reporting this, you're absolutely right, torch is being added because sentence-transformers which is a test dependency and was in the wrong poetry dependency group. This should be fixed in the next release 0.0.3. Cheers!

**Comment by bsbodden** [comment]
This should be available in https://pypi.org/project/langchain-redis/ v0.0.3
